version: "3"



services:



  app:

    container_name: airflow_ml_model

    build: .

    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:

      - .:/app

    ports:

      - 8000:8000
      